apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: my-container
        image: tweeter-app
        command: ["/bin/sh", "-c"]
        args: ["python data_ingestion.py && data_processing.py && data_analysis.py"]